CREATE TABLE DEMANDE (
    ID_DEMANDE INT NOT NULL AUTO_INCREMENT,
	MOTIF VARCHAR(255),
	DATE_DEMANDE DATETIME,
	ETAT ENUM ('EN_COURS','TRAITE'),
	CONSTRAINT PK_ID_DEMANDE PRIMARY KEY(ID_DEMANDE)
);

INSERT INTO DEMANDE (MOTIF, DATE_DEMANDE, ETAT) VALUES ('Demande atestation de salaire', '2019-03-20 17:52:45','EN_COURS');

INSERT INTO DEMANDE (MOTIF, DATE_DEMANDE, ETAT) VALUES ('Demande atestation de travail', '2019-03-14 15:25:05','EN_COURS');
