CREATE TABLE TYPE_DOCUMENT(
    ID_TYPE_DOCUMENT INT NOT NULL AUTO_INCREMENT,
	LIBELLE VARCHAR(255),
	CONSTRAINT PK_ID_DEMANDE PRIMARY KEY(ID_TYPE_DOCUMENT)
);

INSERT INTO TYPE_DOCUMENT (LIBELLE) VALUES ('Atestation de salaire');
INSERT INTO TYPE_DOCUMENT (LIBELLE) VALUES ('Atestation de travail');

