CREATE TABLE DOCUMENT(
    ID_DOCUMENT INT NOT NULL AUTO_INCREMENT,
	LIBELLE VARCHAR(255),
	ID_TYPE_DOCUMENT INT NOT NULL,
	ID_DEMANDE INT NOT NULL,
	
	CONSTRAINT PK_ID_DEMANDE PRIMARY KEY(ID_DOCUMENT),
	CONSTRAINT FK_TYPE_DOCUMENT FOREIGN KEY (ID_TYPE_DOCUMENT) REFERENCES TYPE_DOCUMENT(ID_TYPE_DOCUMENT),
	CONSTRAINT FK_DEMANDE FOREIGN KEY (ID_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE)
);

INSERT INTO DOCUMENT (LIBELLE , ID_TYPE_DOCUMENT, ID_DEMANDE) VALUES ('Atestation de salaire',1 ,1);

INSERT INTO DOCUMENT (LIBELLE , ID_TYPE_DOCUMENT, ID_DEMANDE) VALUES ('Atestation de travail',2 ,2);



